env: dev
debug: true
application: viper-example

host:
port: 9090
shutDownTimeout: 5
language: cn
swagger: true
enableRtPool: true

log:
  level: DEBUG
  enableConsole: true
  rotated: true
  fileDir:
  maxSize: 1
  maxAge: 7
  localtime: true
  compress: true

db:
  host: 127.0.0.1
  port: 3306
  user: jh
  password: 123456
  dbType: mysql
  database: demo_shiyanlou
  location: UTC
  tablePrefix:
  singularTable: true
  createBatchSize: 1000
  enableRawSql: true
  maxFreeConnCount: 1
  maxOpenConnCount: 1
  freeMaxLifetime: 30

cache:
  host: 127.0.0.1
  port: 6379
  pwd: 123456
  minFreeConnCount: 1
  maxFreeConnCount: 1
  maxOpenConnCount: 1
  freeMaxLifetime: 30
  database: 0
  connectTimeout: 3
  readTimeout: 3
  writeTimeout: 3
